name: Build

# on:
#   push:
#     paths: [ '.github/workflows/build.yml','.github/workflows/buildv.yml','src/**']
#   pull_request:
#     paths: [ '.github/workflows/build.yml','.github/workflows/buildv.yml','src/**']

on:
  workflow_dispatch:

jobs:
  buildv:
    uses: ./.github/workflows/buildv.yml
  